import { Platform } from 'react-native';

import {
  IColorTheme,
  IFontTheme,
  ISpacingTheme,
  ITheme,
} from './theme.interface';
import { resizeHeight, resizeWidth } from './utils';

const fonts = {
  primaryLight: 'default',
  primaryRegular: 'default',
  primaryBold: 'default',
  primarySemiBold: 'default',
};

const DEFAULT_COLOR_THEME: IColorTheme = {
  primary: '#4CAF50',
  primaryDarker: '#3F35D4',
  primaryDark: '#1B00A6',
  primaryDisabled: '#F1F5F9',
  secondary: '#ECE8FF',
  secondaryDark: '#DAD4FF',
  tertiaryDarker: '#F8FAFC',
  white: '#FFFFFF',
  whiteDisabled: '#CBD5E1',
  inputFocused: '#94A3B8',
  black: '#000000',
  main: '#1a1a2e',
  subText: '#666666',
  placeholder: '#999999',
  gray900: '#141414',
  gray800: '#1F1F1F',
  gray700: '#333333',
  gray600: '#545454',
  gray500: '#757575',
  gray400: '#AFAFAF',
  gray300: '#CBCBCB',
  gray200: '#E2E2E2',
  gray100: '#EEEEEE',
  transparent: 'transparent',
  validColor: '#00B505',
  successColor: '#4CAF50',
  errorColor: '#F44336',
  errorDark: '#AF4C4C',
  warningColor: '#FF9800',
  info: '#2196F3',
  border: '#DDDDDD',
  background: '#f9f9f9',
  bgInfo: '#F5F2FF',
  bgSuccess: '#E8FFE4',
  bgError: '#FFF2F1',
  bgErrorHover: '#FFC8C5',
  bgWarning: '#FFFFE7',
  bgPrimary: '#645AFF',
};

export const DEFAULT_FONTS_THEME: IFontTheme = {
  bold9: {
    fontFamily: fonts.primaryBold,
    fontWeight: '700',
    fontSize: 60,
    lineHeight: Platform.OS === 'android' ? 60 : 0,
  },
  bold8: {
    fontFamily: fonts.primaryBold,
    fontWeight: '700',
    fontSize: 35,
    lineHeight: Platform.OS === 'android' ? 40 : 0,
  },
  bold7: {
    fontFamily: fonts.primaryBold,
    fontWeight: '700',
    fontSize: 28,
    lineHeight: Platform.OS === 'android' ? 36 : 0,
  },
  bold6: {
    fontFamily: fonts.primaryBold,
    fontWeight: '700',
    fontSize: 24,
    lineHeight: Platform.OS === 'android' ? 30 : 0,
  },
  bold5: {
    fontFamily: fonts.primaryBold,
    fontWeight: '700',
    fontSize: 20,
    lineHeight: Platform.OS === 'android' ? 28 : 0,
  },
  bold4: {
    fontFamily: fonts.primaryBold,
    fontWeight: '700',
    fontSize: 18,
    lineHeight: Platform.OS === 'android' ? 26 : 0,
  },
  bold3: {
    fontFamily: fonts.primaryBold,
    fontWeight: '700',
    fontSize: 16,
    lineHeight: Platform.OS === 'android' ? 24 : 0,
  },
  bold2: {
    fontFamily: fonts.primaryBold,
    fontWeight: '700',
    fontSize: 14,
    lineHeight: Platform.OS === 'android' ? 20 : 0,
  },
  bold1: {
    fontFamily: fonts.primaryBold,
    fontWeight: '700',
    fontSize: 12,
    lineHeight: Platform.OS === 'android' ? 16 : 0,
  },

  medium9: {
    fontFamily: fonts.primarySemiBold,
    fontWeight: '500',
    fontSize: 60,
    lineHeight: Platform.OS === 'android' ? 60 : 0,
  },
  medium8: {
    fontFamily: fonts.primarySemiBold,
    fontWeight: '500',
    fontSize: 35,
    lineHeight: Platform.OS === 'android' ? 40 : 0,
  },
  medium7: {
    fontFamily: fonts.primarySemiBold,
    fontWeight: '500',
    fontSize: 28,
    lineHeight: 36,
  },
  medium6: {
    fontFamily: fonts.primarySemiBold,
    fontWeight: '500',
    fontSize: 24,
    lineHeight: Platform.OS === 'android' ? 30 : 0,
  },
  medium5: {
    fontFamily: fonts.primarySemiBold,
    fontWeight: '500',
    fontSize: 20,
    lineHeight: Platform.OS === 'android' ? 28 : 0,
  },
  medium4: {
    fontFamily: fonts.primarySemiBold,
    fontWeight: '500',
    fontSize: 18,
    lineHeight: Platform.OS === 'android' ? 26 : 0,
  },
  medium3: {
    fontFamily: fonts.primarySemiBold,
    fontWeight: '500',
    fontSize: 16,
    lineHeight: Platform.OS === 'android' ? 24 : 0,
  },
  medium2: {
    fontFamily: fonts.primarySemiBold,
    fontWeight: '500',
    fontSize: 14,
    lineHeight: Platform.OS === 'android' ? 20 : 0,
  },
  medium1: {
    fontFamily: fonts.primarySemiBold,
    fontWeight: '500',
    fontSize: 12,
    lineHeight: Platform.OS === 'android' ? 16 : 0,
  },
  regular9: {
    fontFamily: fonts.primaryRegular,
    fontWeight: '400',
    fontSize: 60,
    lineHeight: Platform.OS === 'android' ? 60 : 0,
  },
  regular8: {
    fontFamily: fonts.primaryRegular,
    fontWeight: '400',
    fontSize: 35,
    lineHeight: Platform.OS === 'android' ? 40 : 0,
  },
  regular7: {
    fontFamily: fonts.primaryRegular,
    fontWeight: '400',
    fontSize: 28,
    lineHeight: Platform.OS === 'android' ? 36 : 0,
  },
  regular6: {
    fontFamily: fonts.primaryRegular,
    fontWeight: '400',
    fontSize: 24,
    lineHeight: Platform.OS === 'android' ? 30 : 0,
  },
  regular5: {
    fontFamily: fonts.primaryRegular,
    fontWeight: '400',
    fontSize: 20,
    lineHeight: Platform.OS === 'android' ? 28 : 0,
  },
  regular4: {
    fontFamily: fonts.primaryRegular,
    fontWeight: '400',
    fontSize: 18,
    lineHeight: Platform.OS === 'android' ? 26 : 0,
  },
  regular3: {
    fontFamily: fonts.primaryRegular,
    fontWeight: '400',
    fontSize: 16,
    lineHeight: Platform.OS === 'android' ? 24 : 0,
  },
  regular2: {
    fontFamily: fonts.primaryRegular,
    fontWeight: '400',
    fontSize: 14,
    lineHeight: Platform.OS === 'android' ? 20 : 0,
  },
  regular1: {
    fontFamily: fonts.primaryRegular,
    fontWeight: '400',
    fontSize: 12,
    lineHeight: Platform.OS === 'android' ? 16 : 0,
  },
  light9: {
    fontFamily: fonts.primaryLight,
    fontWeight: '300',
    fontSize: 60,
    lineHeight: Platform.OS === 'android' ? 60 : 0,
  },
  light8: {
    fontFamily: fonts.primaryLight,
    fontWeight: '300',
    fontSize: 35,
    lineHeight: Platform.OS === 'android' ? 40 : 0,
  },
  light7: {
    fontFamily: fonts.primaryLight,
    fontWeight: '300',
    fontSize: 28,
    lineHeight: Platform.OS === 'android' ? 36 : 0,
  },
  light6: {
    fontFamily: fonts.primaryLight,
    fontWeight: '300',
    fontSize: 24,
    lineHeight: Platform.OS === 'android' ? 30 : 0,
  },
  light5: {
    fontFamily: fonts.primaryLight,
    fontWeight: '300',
    fontSize: 20,
    lineHeight: Platform.OS === 'android' ? 28 : 0,
  },
  light4: {
    fontFamily: fonts.primaryLight,
    fontWeight: '400',
    fontSize: 18,
    lineHeight: Platform.OS === 'android' ? 26 : 0,
  },
  light3: {
    fontFamily: fonts.primaryLight,
    fontWeight: '300',
    fontSize: 16,
    lineHeight: Platform.OS === 'android' ? 24 : 0,
  },
  light2: {
    fontFamily: fonts.primaryLight,
    fontWeight: '300',
    fontSize: 14,
    lineHeight: Platform.OS === 'android' ? 20 : 0,
  },
  light1: {
    fontFamily: fonts.primaryLight,
    fontWeight: '300',
    fontSize: 12,
    lineHeight: Platform.OS === 'android' ? 16 : 0,
  },
};
export const DEFAULT_SPACING_THEME: ISpacingTheme = {
  xSmall: 8,
  small: 12,
  medium: 16,
  large: 20,
  xLarge: 24,
  xxLarge: 40,
};
const DARK_COLOR_THEME: IColorTheme = {
  primary: '#4CAF50',
  primaryDarker: '#5C4DFF',
  primaryDark: '#7C6BFF',
  primaryDisabled: '#1E293B',
  secondary: '#2A2040',
  secondaryDark: '#3A3050',
  tertiaryDarker: '#1A1A2E',
  white: '#1E1E2E',
  whiteDisabled: '#333344',
  inputFocused: '#64748B',
  black: '#FFFFFF',
  main: '#E4E4E7',
  subText: '#A1A1AA',
  placeholder: '#71717A',
  gray900: '#F4F4F5',
  gray800: '#E4E4E7',
  gray700: '#D4D4D8',
  gray600: '#A1A1AA',
  gray500: '#71717A',
  gray400: '#52525B',
  gray300: '#3F3F46',
  gray200: '#27272A',
  gray100: '#18181B',
  transparent: 'transparent',
  validColor: '#00B505',
  successColor: '#4CAF50',
  errorColor: '#F44336',
  errorDark: '#CF6679',
  warningColor: '#FF9800',
  info: '#64B5F6',
  border: '#3F3F46',
  background: '#0F0F14',
  bgInfo: '#1E1E3F',
  bgSuccess: '#1A2E1A',
  bgError: '#2E1A1A',
  bgErrorHover: '#3E2020',
  bgWarning: '#2E2E1A',
  bgPrimary: '#645AFF',
};

export const DEFAULT_THEME_ID = 'default';
export const DARK_THEME_ID = 'dark';

export const DEFAULT_THEME: ITheme = {
  id: DEFAULT_THEME_ID,
  color: DEFAULT_COLOR_THEME,
  spacing: DEFAULT_SPACING_THEME,
  fonts: DEFAULT_FONTS_THEME,
  shouldResize: false,
  resizeWidth,
  resizeHeight,
};

export const DARK_THEME: ITheme = {
  id: DARK_THEME_ID,
  color: DARK_COLOR_THEME,
  spacing: DEFAULT_SPACING_THEME,
  fonts: DEFAULT_FONTS_THEME,
  shouldResize: false,
  resizeWidth,
  resizeHeight,
};
